python pipeline.py \
    --input_path /path/to/wiki \
    --category Airport \
    --output_path /path/to/output.json \
    --ner_path /path/to/ner_model \
    --attribute_path /path/to/attribute_dir \
    --model_name cl-tohoku/bert-base-japanese \
    --biencoder_path biencoder.model \
    --crossencoder_path crossencoder.model \
    --max_ctxt_len 32 \
    --max_title_len -1 \
    --max_desc_len 128 \
    --candidate_dataset /path/to/candidates.jsonl \
    --index_path /path/to/faiss_candidates \
    --builder_gpu \
    --faiss_gpu_id 0 \
    --parallel \
    --fp16 \
    --fp16_opt_level O1